name: Debugger builder

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release'
        required: false

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Electron project dependencies
        run: |
          cd debugger
          yarn install
          yarn build

      - name: Build Electron project [macOS]
        run: |
          cd debugger
          yarn dist --mac

      - name: Build Electron project [linux]
        run: |
          cd debugger
          yarn dist --linux

      - name: Build Electron project [win]
        run: |
          cd debugger
          yarn dist --win

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.release }}
          release_name: Release ${{ github.event.inputs.release }}
          draft: false
          prerelease: false

      - name: Upload Release Asset [macOS]
        id: upload-release-asset-mac
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./debugger/dist/Sveltotron.dmg
          asset_name: Sveltotron.dmg
          asset_content_type: application/octet-stream

      - name: Upload Release Asset [linux/snap]
        id: upload-release-asset-linux-snap
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./debugger/dist/Sveltotron.snap
          asset_name: Sveltotron.snap
          asset_content_type: application/octet-stream

      - name: Upload Release Asset [linux/AppImage]
        id: upload-release-asset-linux-app
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./debugger/dist/Sveltotron.AppImage
          asset_name: Sveltotron.AppImage
          asset_content_type: application/x-executable

      - name: Upload Release Asset [win]
        id: upload-release-asset-win
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./debugger/dist/Sveltotron.exe
          asset_name: Sveltotron.exe
          asset_content_type: application/x-dosexec
